name: prometheus-juju-exporter
base: core22
adopt-info: prometheus-juju-exporter
# version: "0.1"
summary: collects and exports juju machine status metrics
description: |
  Collects juju machine status metrics periodically.
  Provides a prometheus exporter interface exposing the collected metrics.
architectures:
  - build-on: amd64

grade: stable
confinement: strict

apps:
  prometheus-juju-exporter:
    daemon: simple
    restart-condition: on-failure
    restart-delay: 30s
    command: bin/prometheus-juju-exporter
    plugs: [network, network-bind]
    environment:
        PROMETHEUSJUJUEXPORTERDIR: $SNAP_DATA/

parts:
  prometheus-juju-exporter:
    plugin: python
    source: .
    python-requirements: [./requirements.txt]
    python-packages:
      - .
    override-build: |
        snapcraftctl build
        echo "Version: $(python3 setup.py --version)"
        snapcraftctl set-version "$(python3 setup.py --version)"
