name: Functional tests
on:
  pull_request_review:
    types: [ submitted ]
jobs:
  functest:
    name: Functional tests
    runs-on: ubuntu-latest
    if: >-
      github.event.review.state == 'approved'
      || github.event.review.body == 'recheck'
      || github.event.review.body == 'recheck-full'
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install tox
        run: pip install "tox < 4" #tox has breaking changes in major version 4
      - name: Set up LXD
        uses: canonical/setup-lxd@90d76101915da56a42a562ba766b1a77019242fd
      - name: Install and bootstrap juju
        run: |
          sudo snap install juju --classic --channel=2.9/stable
          juju bootstrap lxd localcloud
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - name: Run functional tests
        run: make functional
