name: Promote snap to other tracks and channels

on:
  workflow_dispatch:
    inputs:
      destination-channel:
        description: 'Destination Channel'
        required: true
      origin-channel:
        description: 'Origin Channel'
        required: true

jobs:
  promote-snap:
    name: Promote snap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        run: sudo apt update && sudo apt install yq -y
      - name: Snapcraft install
        run: sudo snap install --classic snapcraft
      - name: Snapcraft login
        run: snapcraft login --with ${{ secrets.STORE_LOGIN }}
      - name: Get snap name
        id: snap
        run: echo "name=$(yq '.name' snap/snapcraft.yaml)" >> $GITHUB_OUTPUT
      - name: Snapcraft promote snap
        run: |
          snapcraft ${{ steps.snap.outputs.name }}  \
          --from-channel ${{ github.event.inputs.origin-channel }} \
          --to-channel ${{ github.event.inputs.destination-channel }} \
          --yes
      - name: Snapcraft logout
        run: snapcraft logout
